apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2017-08-19T18:24:11Z
  labels:
    kops.k8s.io/cluster: {{ settings.provision.domain }}
  name: master-{{ settings.aws_zone }}
spec:
  image: kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2018-08-17
  machineType: {{ settings.provision.master.machineType }}
  maxSize: {{ settings.provision.master.maxSize }}
  minSize: {{ settings.provision.master.minSize }}
  additionalSecurityGroups:
  - {{ settings.provision.master.additionalSecurityGroups }}
  nodeLabels:
    kops.k8s.io/instancegroup: master-{{ settings.aws_zone }}
  role: Master
  subnets:
  - {{ settings.aws_zone }}
  rootVolumeSize: {{ settings.provision.master.rootVolumeSize }}
  rootVolumeType: {{ settings.provision.master.rootVolumeType }}
  rootVolumeIops: {{ settings.provision.master.rootVolumeIops }}
  rootVolumeOptimization: {{ settings.provision.master.rootVolumeOptimization }}
  cloudLabels:
    environment: {{ settings.cluster.name.upper() }}
  additionalUserData:
  - name: startup.sh
    type: text/x-shellscript
    content: |
      #!/bin/bash
      sudo apt-get update
      sudo apt-get install nfs-kernel-server -y