---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: neo4j-tls
  namespace: neo4j
spec:
  secretName: neo4j-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: neo4j.{{ settings.provision.domain }}
  dnsNames:
  - neo4j.{{ settings.provision.domain }}
  acme:
    config:
    - dns01:
        provider: route53
      domains:
      - neo4j.{{ settings.provision.domain }}
