---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: neo4j
  name: neo4j
  annotations:
#    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
#    certmanager.k8s.io/cluster-issuer: letsencrypt-staging
#    kubernetes.io/tls-acme: 'true'
    ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - signin.{{ settings.provision.domain }}
    secretName: neo4j-tls
  rules:
  - host: signin.{{ settings.provision.domain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: neo4j
          servicePort: 7474
