---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: jenkins
  name: jenkins
  annotations:
#    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
#    certmanager.k8s.io/cluster-issuer: letsencrypt-staging
#    kubernetes.io/tls-acme: 'true'
    ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - jenkins.mad.rest
    secretName: jenkins-tls
  rules:
  - host: jenkins.mad.rest
    http:
      paths:
      - path: /
        backend:
          serviceName: jenkins
          servicePort: 7474
