---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  namespace: scrapy
  labels:
    app: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: zookeeper
        ports:
        - containerPort: 2181
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: scrapy
  labels:
    app: zookeeper
spec:
  ports:
  - name: zookeeper
    port: 2181
  selector:
    app: zookeeper

